"""init

Revision ID: 4b13f6bbf71c
Revises: 
Create Date: 2026-04-16 11:38:17.656938

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel




# revision identifiers, used by Alembic.
revision = '4b13f6bbf71c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('legal_representative_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agency_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('administration_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('office_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_date', sa.Date(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=True),
    sa.Column('billing_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingfrequency'), nullable=False),
    sa.Column('payment_method', sa.Enum('TRANSFER', 'CREDIT_CARD', 'DEBIT', 'CHECK', name='paymentmethod'), nullable=False),
    sa.Column('tax_condition', sa.Enum('RESPONSABLE_INSCRIPTO', 'MONOTRIBUTO', 'EXENTO', 'CONSUMIDOR_FINAL', name='taxcondition'), nullable=False),
    sa.Column('bank_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ssn_register', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_agency_email'), 'agencies', ['agency_email'], unique=False)
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
    op.create_index(op.f('ix_agencies_tax_id'), 'agencies', ['tax_id'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'AGENCY', 'SELLER', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('sellers',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_user_id'), 'sellers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_user_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agencies_tax_id'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_agency_email'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###

